name: Release

on:
  push:
    tags: ["*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  publish-github:
    name: Publish to GitHub
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    with:
      generate: false
      attestations: true

  publish-cargo:
    name: Publish to Crates.io
    if: needs.release-please.outputs.release_created
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
    secrets:
      CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
    with:
      generate: false

  publish-npm:
    name: Publish to npm
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
    with:
      generate: false
